//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8941
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace RFC
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;


    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'EndpointReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/08/addressing'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ZWS_SD_F_GET_A_RFC_DETAIL", 
        Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ZSdFGetARfcDetailOperationCompleted;

        /// <remarks/>
        public service()
        {
            this.Url = "http://yidevqa.yichang.com.pe:8000/sap/bc/srt/rfc/sap/zws_sd_f_get_a_rfc_detail/600/zws_sd_f_get_a_rfc_detail/zws_sd_f_get_a_rfc_detail";
        }

        /// <remarks/>
        public event ZSdFGetARfcDetailCompletedEventHandler ZSdFGetARfcDetailCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, 
            ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZSdFGetARfcDetailResponse", Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZSdFGetARfcDetailResponse ZSdFGetARfcDetail([System.Xml.Serialization.XmlElementAttribute("ZSdFGetARfcDetail", Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")] ZSdFGetARfcDetail ZSdFGetARfcDetail1)
        {
            object[] results = this.Invoke("ZSdFGetARfcDetail", new object[] {
                        ZSdFGetARfcDetail1});
            return ((ZSdFGetARfcDetailResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginZSdFGetARfcDetail(ZSdFGetARfcDetail ZSdFGetARfcDetail1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ZSdFGetARfcDetail", new object[] {
                        ZSdFGetARfcDetail1}, callback, asyncState);
        }

        /// <remarks/>
        public ZSdFGetARfcDetailResponse EndZSdFGetARfcDetail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZSdFGetARfcDetailResponse)(results[0]));
        }

        /// <remarks/>
        public void ZSdFGetARfcDetailAsync(ZSdFGetARfcDetail ZSdFGetARfcDetail1)
        {
            this.ZSdFGetARfcDetailAsync(ZSdFGetARfcDetail1, null);
        }

        /// <remarks/>
        public void ZSdFGetARfcDetailAsync(ZSdFGetARfcDetail ZSdFGetARfcDetail1, object userState)
        {
            if ((this.ZSdFGetARfcDetailOperationCompleted == null))
            {
                this.ZSdFGetARfcDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZSdFGetARfcDetailOperationCompleted);
            }
            this.InvokeAsync("ZSdFGetARfcDetail", new object[] {
                        ZSdFGetARfcDetail1}, this.ZSdFGetARfcDetailOperationCompleted, userState);
        }

        private void OnZSdFGetARfcDetailOperationCompleted(object arg)
        {
            if ((this.ZSdFGetARfcDetailCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZSdFGetARfcDetailCompleted(this, new ZSdFGetARfcDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZSdFGetARfcDetail
    {

        private string imVBukrsField;

        private string imVDatumField;

        private string imVIdfunctField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImVBukrs
        {
            get
            {
                return this.imVBukrsField;
            }
            set
            {
                this.imVBukrsField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImVDatum
        {
            get
            {
                return this.imVDatumField;
            }
            set
            {
                this.imVDatumField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImVIdfunct
        {
            get
            {
                return this.imVIdfunctField;
            }
            set
            {
                this.imVIdfunctField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstSdGetFunction
    {

        private string idfunctField;

        private string getfuncField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Idfunct
        {
            get
            {
                return this.idfunctField;
            }
            set
            {
                this.idfunctField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Getfunc
        {
            get
            {
                return this.getfuncField;
            }
            set
            {
                this.getfuncField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZSdFGetARfcDetailResponse
    {

        private ZstSdGetFunction exWaXmlField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZstSdGetFunction ExWaXml
        {
            get
            {
                return this.exWaXmlField;
            }
            set
            {
                this.exWaXmlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ZSdFGetARfcDetailCompletedEventHandler(object sender, ZSdFGetARfcDetailCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZSdFGetARfcDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        private object[] results;
        internal ZSdFGetARfcDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ZSdFGetARfcDetailResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ZSdFGetARfcDetailResponse)(this.results[0]));
            }
        }
    }
}
